
package project.wsdl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerServiceWS", targetNamespace = "http://dcproject3.org/wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerServiceWS {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkLogin", targetNamespace = "http://dcproject3.org/wsdl", className = "project.CheckLogin")
    @ResponseWrapper(localName = "checkLoginResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.CheckLoginResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/checkLoginRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/checkLoginResponse")
    public boolean checkLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.util.List<project.DoctorInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDoctors", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetAllDoctors")
    @ResponseWrapper(localName = "getAllDoctorsResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetAllDoctorsResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/getAllDoctorsRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/getAllDoctorsResponse")
    public List<DoctorInfo> getAllDoctors();

    /**
     * 
     * @param arg0
     * @return
     *     returns project.DoctorInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorByID", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetDoctorByID")
    @ResponseWrapper(localName = "getDoctorByIDResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetDoctorByIDResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/getDoctorByIDRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/getDoctorByIDResponse")
    public DoctorInfo getDoctorByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeAppointment", targetNamespace = "http://dcproject3.org/wsdl", className = "project.MakeAppointment")
    @ResponseWrapper(localName = "makeAppointmentResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.MakeAppointmentResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/makeAppointmentRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/makeAppointmentResponse")
    public boolean makeAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<project.MedicalRecord>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMedicalRecord", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetMedicalRecord")
    @ResponseWrapper(localName = "getMedicalRecordResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetMedicalRecordResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/getMedicalRecordRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/getMedicalRecordResponse")
    public List<MedicalRecord> getMedicalRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<project.DepartmentInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDepartments", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetAllDepartments")
    @ResponseWrapper(localName = "getAllDepartmentsResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetAllDepartmentsResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/getAllDepartmentsRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/getAllDepartmentsResponse")
    public List<DepartmentInfo> getAllDepartments();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<project.DoctorInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDoctorsByDepartment", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetDoctorsByDepartment")
    @ResponseWrapper(localName = "getDoctorsByDepartmentResponse", targetNamespace = "http://dcproject3.org/wsdl", className = "project.GetDoctorsByDepartmentResponse")
    @Action(input = "http://dcproject3.org/wsdl/CustomerServiceWS/getDoctorsByDepartmentRequest", output = "http://dcproject3.org/wsdl/CustomerServiceWS/getDoctorsByDepartmentResponse")
    public List<DoctorInfo> getDoctorsByDepartment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
